export const EDIT_SURVEY_ADD_QUESTION = 'EDIT_SURVEY_ADD_QUESTION';
export const EDIT_SURVEY_SWITCH_TAB = 'EDIT_SURVEY_SWITCH_TAB';
export const ACTIVE_QUESTION = 'ACTIVE_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const SORT_QUESTION = 'SORT_QUESTION';
export const SORT_QUESTION_UP = 'SORT_QUESTION_UP';
export const SORT_QUESTION_DOWN = 'SORT_QUESTION_DOWN';
export const CLONE_QUESTION = 'CLONE_QUESTION';
export const EDIT_SURVEY_UPDATE_QUESTION = 'EDIT_SURVEY_UPDATE_QUESTION';
export const EDIT_SURVEY_UPDATE_SURVEY_HEADER =
  'EDIT_SURVEY_UPDATE_SURVEY_HEADER';
// export const

export const FETCH_SURVEYS_REQUEST = 'FETCH_SURVEYS_REQUEST';
export const FETCH_SURVEYS_REQUEST_SUCCESS = 'FETCH_SURVEYS_REQUEST_SUCCESS';
export const FETCH_SURVEYS_REQUEST_FAIL = 'FETCH_SURVEYS_REQUEST_FAIL';

export const CREATE_SURVEY_REQUEST_SUCCESS = 'CREATE_SURVEY_REQUEST_SUCCESS';
export const CREATE_SURVEY_REQUEST_FAIL = 'CREATE_SURVEY_REQUEST_FAIL';
export const CREATE_SURVEY_REQUEST = 'CREATE_SURVEY_REQUEST';
